export const MESSAGE = {
  START_SCORING: 'START_SCORING',
  STOP_SCORING: 'STOP_SCORING',
  GET_SCORING_STATUS: 'GET_SCORING_STATUS',
  CLEAR_CACHE: 'CLEAR_CACHE',
  SCORING_STARTED: 'SCORING_STARTED',
  SCORING_PROGRESS: 'SCORING_PROGRESS',
  SCORING_COMPLETE: 'SCORING_COMPLETE',
  PROFILES_FOUND: 'PROFILES_FOUND',
  EXTRACTION_ERROR: 'EXTRACTION_ERROR',
  EXTRACT_NOW: 'EXTRACT_NOW',
};

export const RETRY_COUNT = 3;
export const MIN_TEXT_LENGTH = 50;
export const PROFILE_TIMEOUT_MS = 60000;
export const SCORING_DELAY_MS = 3000;
export const BATCH_SIZE = 3;
export const CACHE_EXPIRY_MS = 86400000;
